#
# Makefile for cice processing
#
# --- usage: make grid2cice ARCH=sun >& Make_grid2cice
#
# --- Tunable parameters in ../../config/$(ARCH)_setup
#

.SUFFIXES: 
.SUFFIXES: .c .F .f .o .F90

.F:
	@echo "Must have an explicit rule for" $*
	@exit 1
.f:
	@echo "Must have an explicit rule for" $*
	@exit 1
.c:
	@echo "Must have an explicit rule for" $*
	@exit 1

include config/$(ARCH)_setup

#
# ---------------------------------------------------------------------
# Standard part of the Makefile starts here
# ---------------------------------------------------------------------
#

clean:
	/bin/rm -f *.o *.mod xhycom

MODS = param.o field_defs.o cdf.o mod_za.o zh.o 

#GRID_OBJ = 	blkin.o  \
#		zh.o    dum_gks.o 


#ARCHV_OBJ = 	bigrid.o blkin.o  \
#		forday.o  \
#                putdat.o \
#		zh.o    dum_gks.o 

#
# --- executables.
#

xhycom: $(MODS) XHygrid.o $(GRID_OBJ)
	$(LD) $(LDFLAGS) -o xhycom   XHygrid.o  -I$(CDF)/include $(GRID_OBJ)  $(MODS) $(EXTRALIBS)

#
# --- explicit dependencies for each .[fF] file.
#

cdf.o: param.o field_defs.o
field_defs.o: param.o 
mod_za.o : zh.o
XHygrid.o : param.o cdf.o mod_za.o

#cice_tiles.o:       cice_tiles.F
#cice2hycom.o:       cice2hycom.f                  mod_za.o
#cice2archv.o:       cice2archv.f       mod_cice.o mod_za.o
#grid2cice.o:        grid2cice.f        mod_cice.o mod_za.o

#bigrid.o:   bigrid.f      mod_cice.o
#blkin.o:    blkin.f
#dum_gks.o:  dum_gks.f
#forday.o:   forday.f
#putdat.o:   putdat.f      mod_cice.o mod_za.o
#wtime.o:    wtime.F

#mod_cice.o: mod_cice.F
#mod_xc.o:   mod_xc.F   
#mod_za.o:   mod_za.F   mod_xc.o

#zh.o:       zh.F zh_sun.f zh_t3e.f zh_ymp.f
