#! /bin/sh
#

usage()  {
  echo "USAGE:     mergelib [-h] [-d indir] [-o ofile] [file...]" >&2
  echo "" >&2
  echo "           -h ; print this summary" >&2
  echo "           -d ; indir ; input directory, default = current directory" >&2
  echo "           -o ; ofile ; output file, default is standard output" >&2
  echo "           file... ; files to merge, default = *.[hfFc]" >&2
}


bn() {
  IFS_SAVE="$IFS"
  IFS="/"
  for xfile in $pathname
  do
    pathname=$xfile
  done
  IFS="$IFS_SAVE"
}

set -- `getopt hd:o: $* 2>/dev/null`
if [ $? != 0 ]
then
  usage
  exit 1
fi

indir=`pwd`
ofile=

while [ -n "$1" ]
do
  case $1 in
       -h) usage
           exit;;
       -d) indir=$2
           shift 2;;
       -o) ofile=$2
           shift 2;;
       --) shift;;
        *) decks=$*
           break;;
  esac
done

if [ ! -d $indir ]
then
  echo "$indir not a directory" >&2
  exit 1
fi
if [ ! -w $indir -o ! -x $indir ]
then
  echo "$indir:  permission denied" >&2
  exit 1
fi
if [ -n "$ofile" ]
then
  exec > $ofile
fi

cd $indir
if [ -n "$decks" ]
then

  for file in $decks
  do
    pathname=$file ; bn
    echo "#DECK $pathname"
    cat $file
  done

else

  hfiles=`echo *.h`
  if [ "$hfiles" != "*.h" ]
  then
    for file in $hfiles
    do
      pathname=$file ; bn
      echo "#DECK $pathname"
      cat $file
    done
  fi

  sfiles=`echo *.[fFc]`
  if [ "$sfiles" != "*.[fFc]" ]
  then
    for file in $sfiles
    do
      pathname=$file ; bn
      echo "#DECK $pathname"
      cat $file
    done
  fi

fi
